In [1]:
text = "I love NLP and Python programming!"

In [2]:
from typing import Any

Q1)Word Frequency Counter

In [3]:
word_counter ={}
for words in text.split():
    word_counter[words] = word_counter.get(words, 0) + 1
print(word_counter)

{'I': 1, 'love': 1, 'NLP': 1, 'and': 1, 'Python': 1, 'programming!': 1}


Q2)Vocabulary Builder

In [4]:
# for a simple text split
set(text.split())

{'I', 'NLP', 'Python', 'and', 'love', 'programming!'}

In [5]:
# for complex data type 
corpus: list[str] = [
"I like NLP",
"I like AI",
"AI is amazing"
]

vocabulary_set = set()
for sentence in corpus:
    vocabulary_set.update(sentence.split())

print(vocabulary_set)

length_of_vocab = len(vocabulary_set)
print("The vocabulary size of the corpus is", length_of_vocab)

{'I', 'NLP', 'is', 'amazing', 'like', 'AI'}
The vocabulary size of the corpus is 6


In [6]:
# TODO for more complex data type use recursion to handle all types of data structure
# TODO indexing based vocabulary representation

class VocabularyCounter:
    def __init__(self, value) -> None:
        self.val: Any = value
        self.vocabulary_set = set()

    def process_data_type(self, val=None):
        value = self.val if val is None else val

        if isinstance(value, str):
            self.vocabulary_set.update(value.split())

        elif isinstance(value, list):
            for item in value:
                self.process_data_type(item)

        else:
            raise NotImplementedError(f"{type(value)} not supported")

    def length(self):
        return len(self.vocabulary_set)

Q3)  Build a Word Co-occurrence Matrix

In [7]:
sentence = "the cat sat on the mat"

In [8]:
vocab_generator = VocabularyCounter(sentence)
vocab_generator.process_data_type()
print(vocab_generator.vocabulary_set)

length_of_vocab = vocab_generator.length()
ordered_vocabulary = sorted(vocab_generator.vocabulary_set)
print(length_of_vocab)


{'the', 'on', 'cat', 'sat', 'mat'}
5


In [9]:
print(ordered_vocabulary)
vocab_dictionary = {word: index for index, word in enumerate(ordered_vocabulary)}
print(vocab_dictionary)

['cat', 'mat', 'on', 'sat', 'the']
{'cat': 0, 'mat': 1, 'on': 2, 'sat': 3, 'the': 4}


In [10]:
import numpy as np

matrix = np.zeros((length_of_vocab, length_of_vocab))

print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
#assign position to each words:
#TODO shift this to a function of vocabulary_counter class
sentence_split = sentence.split()
sentence_length = len(sentence_split)
sentence_encoding = list(enumerate(sentence.split()))
sentence_dictionary = dict(enumerate(sentence.split()))
print(sentence_dictionary)
print(sentence_encoding)


{0: 'the', 1: 'cat', 2: 'sat', 3: 'on', 4: 'the', 5: 'mat'}
[(0, 'the'), (1, 'cat'), (2, 'sat'), (3, 'on'), (4, 'the'), (5, 'mat')]


In [12]:
type(sentence_encoding)

list

In [13]:
for index, value in sentence_encoding:
    window_size = 1
    starting_index = max(index - window_size, 0)
    stopping_index = min(index + window_size, sentence_length - 1)
    print("Index is the current word position in the sentence")
    print(f"index: {index}, value: {value}, window_start: {starting_index}, window_end: {stopping_index}", "with window size of", window_size)
    index_of_current_word = vocab_dictionary[value]
    for i in range(starting_index, stopping_index):
        if i != index:
            matrix[index_of_current_word,list(vocab_dictionary.keys()).index(sentence_dictionary[i])] += 1
            matrix[list(vocab_dictionary.keys()).index(sentence_dictionary[i]),index_of_current_word] += 1

   
print(matrix)


Index is the current word position in the sentence
index: 0, value: the, window_start: 0, window_end: 1 with window size of 1
Index is the current word position in the sentence
index: 1, value: cat, window_start: 0, window_end: 2 with window size of 1
Index is the current word position in the sentence
index: 2, value: sat, window_start: 1, window_end: 3 with window size of 1
Index is the current word position in the sentence
index: 3, value: on, window_start: 2, window_end: 4 with window size of 1
Index is the current word position in the sentence
index: 4, value: the, window_start: 3, window_end: 5 with window size of 1
Index is the current word position in the sentence
index: 5, value: mat, window_start: 4, window_end: 5 with window size of 1
[[0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 1.]
 [1. 0. 1. 0. 0.]
 [1. 1. 1. 0. 0.]]


In [14]:
import pandas as pd

df = pd.DataFrame(matrix, index=ordered_vocabulary, columns=ordered_vocabulary, dtype=int)

In [15]:
print(df)
# no population of mat
# the', 1: 'cat', 2: 'sat', 3: 'on', 4: 'the', 5: 'mat'}


     cat  mat  on  sat  the
cat    0    0   0    1    1
mat    0    0   0    0    1
on     0    0   0    1    1
sat    1    0   1    0    0
the    1    1   1    0    0
