In [1]:
from typing import Any

# Exercise 4: Detect Data Sparsity

## Objective

Find word pairs that never occur together.

In [2]:

class VocabularyCounter:
    def __init__(self, value) -> None:
        self.val: Any = value
        self.vocabulary_set = set()

    def process_data_type(self, val=None):
        value = self.val if val is None else val

        if isinstance(value, str):
            self.vocabulary_set.update(value.split())

        elif isinstance(value, list):
            for item in value:
                self.process_data_type(item)

        else:
            raise NotImplementedError(f"{type(value)} not supported")

    def length(self):
        return len(self.vocabulary_set)
sentence = "the cat sat on the mat"

vocab_generator = VocabularyCounter(sentence)
vocab_generator.process_data_type()
print(vocab_generator.vocabulary_set)

length_of_vocab = vocab_generator.length()
ordered_vocabulary = sorted(vocab_generator.vocabulary_set)
print(length_of_vocab)
print(ordered_vocabulary)
vocab_dictionary = {word: index for index, word in enumerate(ordered_vocabulary)}
print(vocab_dictionary)

{'cat', 'the', 'sat', 'on', 'mat'}
5
['cat', 'mat', 'on', 'sat', 'the']
{'cat': 0, 'mat': 1, 'on': 2, 'sat': 3, 'the': 4}


In [3]:
import numpy as np

matrix = np.zeros((length_of_vocab, length_of_vocab))

print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
sentence_split = sentence.split()
sentence_length = len(sentence_split)
sentence_encoding = list(enumerate(sentence.split()))
sentence_dictionary= dict(enumerate(sentence.split()))
print(sentence_dictionary)
print(sentence_encoding)


{0: 'the', 1: 'cat', 2: 'sat', 3: 'on', 4: 'the', 5: 'mat'}
[(0, 'the'), (1, 'cat'), (2, 'sat'), (3, 'on'), (4, 'the'), (5, 'mat')]


In [5]:
for index, value in sentence_encoding:
    window_size = 1
    starting_index = max(index - window_size, 0)
    stopping_index = min(index + window_size, sentence_length - 1)
    print(f"index: {index}, value: {value}, starting_index: {starting_index}, stopping_index: {stopping_index}")
    index_of_current_word = vocab_dictionary[value]
    for i in range(starting_index, stopping_index):
        if i != index:
            matrix[index_of_current_word,list(vocab_dictionary.keys()).index(sentence_dictionary[i])] += 1
            matrix[list(vocab_dictionary.keys()).index(sentence_dictionary[i]),index_of_current_word] += 1

   
print(matrix)


index: 0, value: the, starting_index: 0, stopping_index: 1
index: 1, value: cat, starting_index: 0, stopping_index: 2
index: 2, value: sat, starting_index: 1, stopping_index: 3
index: 3, value: on, starting_index: 2, stopping_index: 4
index: 4, value: the, starting_index: 3, stopping_index: 5
index: 5, value: mat, starting_index: 4, stopping_index: 5
[[0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 1.]
 [1. 0. 1. 0. 0.]
 [1. 1. 1. 0. 0.]]


In [6]:
import pandas as pd

df = pd.DataFrame(matrix, index=ordered_vocabulary, columns=ordered_vocabulary, dtype=int)

In [7]:
print(df)

     cat  mat  on  sat  the
cat    0    0   0    1    1
mat    0    0   0    0    1
on     0    0   0    1    1
sat    1    0   1    0    0
the    1    1   1    0    0


# Main Code for finding words that don't occur together

In [19]:
unique_order_of_set = set()
for i in range(length_of_vocab):
    for j in range(length_of_vocab):
        if matrix[i][j] == 0:
            val_a, val_b = sorted([i , j])
            unique_order_of_set.add((val_a, val_b))

print(unique_order_of_set)

for tups in unique_order_of_set:
    i, j = tups
    print(f"Word '{ordered_vocabulary[i]}' doesn't co-occurs with word {ordered_vocabulary[j]}")

{(0, 1), (4, 4), (1, 2), (3, 4), (0, 0), (1, 1), (0, 2), (3, 3), (2, 2), (1, 3)}
Word 'cat' doesn't co-occurs with word mat
Word 'the' doesn't co-occurs with word the
Word 'mat' doesn't co-occurs with word on
Word 'sat' doesn't co-occurs with word the
Word 'cat' doesn't co-occurs with word cat
Word 'mat' doesn't co-occurs with word mat
Word 'cat' doesn't co-occurs with word on
Word 'sat' doesn't co-occurs with word sat
Word 'on' doesn't co-occurs with word on
Word 'mat' doesn't co-occurs with word sat
