In [1]:
text = "I love NLP and Python programming!"

In [6]:
from typing import Any

Q1)Word Frequency Counter

In [2]:
word_counter ={}
for words in text.split():
    word_counter[words] = word_counter.get(words, 0) + 1
print(word_counter)

{'I': 1, 'love': 1, 'NLP': 1, 'and': 1, 'Python': 1, 'programming!': 1}


Q2)Vocabulary Builder

In [3]:
# for a simple text split
set(text.split())

{'I', 'NLP', 'Python', 'and', 'love', 'programming!'}

In [4]:
# for complex data type 
corpus: list[str] = [
"I like NLP",
"I like AI",
"AI is amazing"
]

vocabulary_set = set()
for sentence in corpus:
    vocabulary_set.update(sentence.split())

print(vocabulary_set)

length_of_vocab = len(vocabulary_set)
print("The vocabulary size of the corpus is", length_of_vocab)

{'NLP', 'AI', 'amazing', 'I', 'like', 'is'}
The vocabulary size of the corpus is 6


In [7]:
# TODO for more complex data type use recursion to handle all types of data structure
# TODO indexing based vocabulary representation

class VocabularyCounter:
    def __init__(self, value) -> None:
        self.val: Any = value
        self.vocabulary_set = set()

    def process_data_type(self, val=None):
        value = self.val if val is None else val

        if isinstance(value, str):
            self.vocabulary_set.update(value.split())

        elif isinstance(value, list):
            for item in value:
                self.process_data_type(item)

        else:
            raise NotImplementedError(f"{type(value)} not supported")

    def length(self):
        return len(self.vocabulary_set)

Q3)  Build a Word Co-occurrence Matrix

In [16]:
sentence = "the cat sat on the mat"

In [82]:
vocab_generator = VocabularyCounter(sentence)
vocab_generator.process_data_type()
print(vocab_generator.vocabulary_set)

length_of_sentence = vocab_generator.length()
ordered_vocabulary = sorted(vocab_generator.vocabulary_set)
print(length_of_sentence)
print(ordered_vocabulary)
vocab_dictionary = {word: index for index, word in enumerate(ordered_vocabulary)}
print(vocab_dictionary)

{'cat', 'on', 'mat', 'sat', 'the'}
5
['cat', 'mat', 'on', 'sat', 'the']
{'cat': 0, 'mat': 1, 'on': 2, 'sat': 3, 'the': 4}


In [89]:
import numpy as np

matrix = np.zeros((length_of_sentence, length_of_sentence))

print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [84]:
#assign position to each words:
#TODO shift this to a function of vocabulary_counter class
sentence_encoding = list(enumerate(sentence.split()))
sentence_dictionary= dict(enumerate(sentence.split()))
print(sentence_dictionary)
print(sentence_encoding)

{0: 'the', 1: 'cat', 2: 'sat', 3: 'on', 4: 'the', 5: 'mat'}
[(0, 'the'), (1, 'cat'), (2, 'sat'), (3, 'on'), (4, 'the'), (5, 'mat')]


In [85]:
type(sentence_encoding)

list

In [90]:
for index, value in sentence_encoding:
    window_size = 1
    starting_index = max(index - window_size, 0)
    stopping_index = min(index + window_size, length_of_sentence - 1)
    print(f"index: {index}, value: {value}, starting_index: {starting_index}, stopping_index: {stopping_index}")
    index_of_current_word = vocab_dictionary[value]
    for i in range(starting_index, stopping_index):
        if i != index:
            matrix[index_of_current_word,list(vocab_dictionary.keys()).index(sentence_dictionary[i])] += 1
            matrix[list(vocab_dictionary.keys()).index(sentence_dictionary[i]),index_of_current_word] += 1

   
print(matrix)


index: 0, value: the, starting_index: 0, stopping_index: 1
index: 1, value: cat, starting_index: 0, stopping_index: 2
index: 2, value: sat, starting_index: 1, stopping_index: 3
index: 3, value: on, starting_index: 2, stopping_index: 4
index: 4, value: the, starting_index: 3, stopping_index: 4
index: 5, value: mat, starting_index: 4, stopping_index: 4
[[0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1.]
 [1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0.]]


In [91]:
import pandas as pd

df = pd.DataFrame(matrix, index=ordered_vocabulary, columns=ordered_vocabulary, dtype=int)

In [ ]:
print(df)
# no population of mat
# the', 1: 'cat', 2: 'sat', 3: 'on', 4: 'the', 5: 'mat'}


     cat  mat  on  sat  the
cat    0    0   0    1    1
mat    0    0   0    0    0
on     0    0   0    1    1
sat    1    0   1    0    0
the    1    0   1    0    0
